on:
  release:
    types: [created]
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install virtualenv
      run: |
        if [ `id -u` -eq 0 ]; then
          apt-get update
          apt-get install -y virtualenv python2 zip
        else
          sudo apt-get update
          sudo apt-get install -y virtualenv python2 zip
        fi
    - name: Create python3 venv
      run: |
        virtualenv -p python3 env3
        ./env3/bin/pip install Appium-Python-Client
        ./env3/bin/pip freeze > env3/requirements.txt
        zip sample_env_python3.zip -j env3/requirements.txt
        zip sample_env_python3.zip -r tests
    - name: Create python2 venv
      run: |
        virtualenv -p python2 env2
        ./env2/bin/pip install Appium-Python-Client==0.52
        ./env2/bin/pip freeze > env2/requirements.txt
        zip sample_env_python2.zip -j env2/requirements.txt
        zip sample_env_python2.zip -r tests
#    - name: Build Android app
#      working-directory: ./sample-data/android
#      run: |
#        ./gradlew --no-daemon build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          sample_env_python2.zip
          sample_env_python3.zip
